modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Rongmario/GottaClimbFast/issues"
[[mods]]
modId="gottaclimbfast"
version="1.0"
displayName="Gotta Climb Fast!"
displayURL="https://github.com/Rongmario/GottaClimbFast"
logoFile="icon.png"
authors="Rongmario"
description='''
Climb and descend any kind of climbable block with ease! Now with configurable speeds!
'''
